import {
  SyntheticBank,
  SimulationAttackType,
  SimulationEvent,
} from '../types/simulation';

export const SYNTHETIC_BANKS: SyntheticBank[] = [
  {
    id: 'ALPHA',
    name: 'Bank Alpha',
    city: 'Bengaluru',
    color: '#3157D5', // Sapphire Blue
    bgLight: '#EEF2FF',
    accent: '#2044BD',
    tagline: 'Private Wealth & Corporate Banking',
  },
  {
    id: 'NOVA',
    name: 'Bank Nova',
    city: 'Mumbai',
    color: '#6C63D9', // Soft Violet
    bgLight: '#F3F0FF',
    accent: '#554CB8',
    tagline: 'High-Volume Digital Payment Services',
  },
  {
    id: 'HORIZON',
    name: 'Bank Horizon',
    city: 'Delhi',
    color: '#159A9C', // Teal
    bgLight: '#E6F7F7',
    accent: '#0E7577',
    tagline: 'Commercial & Cross-Border Retail',
  },
];

export function getScenarioEvents(attackType: SimulationAttackType): SimulationEvent[] {
  const now = new Date();
  const formatTime = (offsetSeconds: number) => {
    const d = new Date(now.getTime() + offsetSeconds * 1000);
    return d.toTimeString().split(' ')[0];
  };

  switch (attackType) {
    case 'ACCOUNT_TAKEOVER':
      return [
        {
          id: `SIM-ATO-1-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1003',
          customerName: 'Vikram Malhotra',
          accountId: 'ACC-1003-SAV',
          transactionId: 'TXN-ATO-SEED-01',
          amount: 2400,
          city: 'Bengaluru',
          deviceId: 'DEV-1001-A',
          deviceLabel: 'Known Trusted Mobile',
          ipAddress: '122.167.45.12',
          merchant: 'FreshMart Supermarket',
          timestamp: formatTime(0),
          attackType: 'ACCOUNT_TAKEOVER',
          stepIndex: 1,
          totalSteps: 5,
          riskScore: 0,
          riskLevel: 'LOW',
          decision: 'ALLOW',
          signals: ['Biometric authenticated', 'Known location'],
          summary: 'Normal morning grocery transaction on customer known phone.',
        },
        {
          id: `SIM-ATO-2-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1003',
          customerName: 'Vikram Malhotra',
          accountId: 'ACC-1003-SAV',
          transactionId: 'TXN-ATO-SEED-02',
          amount: 0,
          city: 'Mumbai',
          deviceId: 'DEV-1003-ROGUE',
          deviceLabel: 'Unrecognized Desktop',
          ipAddress: '103.21.144.92',
          merchant: 'Auth Portal / NetBanking',
          timestamp: formatTime(2),
          attackType: 'ACCOUNT_TAKEOVER',
          stepIndex: 2,
          totalSteps: 5,
          riskScore: 15,
          riskLevel: 'LOW',
          decision: 'ALLOW',
          signals: ['New device observed', 'Password failure #1 (01:58)'],
          summary: 'First login failure observed from unregistered desktop.',
        },
        {
          id: `SIM-ATO-3-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1003',
          customerName: 'Vikram Malhotra',
          accountId: 'ACC-1003-SAV',
          transactionId: 'TXN-ATO-SEED-03',
          amount: 0,
          city: 'Mumbai',
          deviceId: 'DEV-1003-ROGUE',
          deviceLabel: 'Unrecognized Desktop',
          ipAddress: '103.21.144.92',
          merchant: 'Auth Portal / NetBanking',
          timestamp: formatTime(4),
          attackType: 'ACCOUNT_TAKEOVER',
          stepIndex: 3,
          totalSteps: 5,
          riskScore: 35,
          riskLevel: 'MEDIUM',
          decision: 'STEP_UP_VERIFICATION',
          signals: ['Multiple password failures', 'Burst window < 2m'],
          summary: 'Pre-auth brute force burst: 2 consecutive password rejections.',
        },
        {
          id: `SIM-ATO-4-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1003',
          customerName: 'Vikram Malhotra',
          accountId: 'ACC-1003-SAV',
          transactionId: 'TXN-ATO-SEED-04',
          amount: 15000,
          city: 'Mumbai',
          deviceId: 'DEV-1003-ROGUE',
          deviceLabel: 'Root/Kali Emulator',
          ipAddress: '103.21.144.92',
          merchant: 'Digital Wallet Load',
          timestamp: formatTime(6),
          attackType: 'ACCOUNT_TAKEOVER',
          stepIndex: 4,
          totalSteps: 5,
          riskScore: 70,
          riskLevel: 'HIGH',
          decision: 'STEP_UP_VERIFICATION',
          signals: ['Datacenter proxy IP', 'Anomalous city', 'Unusual hour (02:11 AM)'],
          summary: 'Compromised session established through proxy IP. Moderate balance probe.',
        },
        {
          id: `SIM-ATO-5-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1003',
          customerName: 'Vikram Malhotra',
          accountId: 'ACC-1003-SAV',
          transactionId: 'TXN-SEED-C1003-FRAUD',
          amount: 85000,
          city: 'Mumbai',
          deviceId: 'DEV-1003-ROGUE',
          deviceLabel: 'Rogue Hardware Fingerprint',
          ipAddress: '103.21.144.92',
          merchant: 'Luxury Jewels & Bullion',
          timestamp: formatTime(8),
          attackType: 'ACCOUNT_TAKEOVER',
          stepIndex: 5,
          totalSteps: 5,
          riskScore: 100,
          riskLevel: 'CRITICAL',
          decision: 'BLOCK_AND_CREATE_CASE',
          signals: [
            'New device',
            '3 failed logins',
            'Unusual hour (02:13 AM)',
            '17× amount deviation',
            'Impossible travel (840 km / 4m)',
            'Datacenter proxy IP',
            'High liquidity bullion MCC'
          ],
          summary: 'Critical account takeover confirmed. Out-of-hours ₹85,000 transfer after credential compromise.',
        },
      ];

    case 'CROSS_BANK_RING':
      return [
        {
          id: `SIM-RING-1-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1002',
          customerName: 'Rohan Mehta',
          accountId: 'ACC-1002-SAV',
          transactionId: 'TXN-RING-ALPHA-75K',
          amount: 75000,
          city: 'Pune',
          deviceId: 'DEV-RING-DEVICE-01',
          deviceLabel: 'Shared Hardware Rig',
          ipAddress: '185.220.101.5',
          merchant: 'PeerTrade P2P Crypto Exchange',
          timestamp: formatTime(0),
          attackType: 'CROSS_BANK_RING',
          stepIndex: 1,
          totalSteps: 3,
          riskScore: 75,
          riskLevel: 'HIGH',
          decision: 'BLOCK_AND_REVIEW',
          signals: ['Shared emulator rig', 'Known proxy subnet', 'High-risk crypto exit'],
          summary: 'Bank Alpha flagged ₹75,000 transfer from shared hardware emulator DEV-RING-DEVICE-01.',
          crossBankCorrelation: {
            sharedDevice: 'DEV-RING-DEVICE-01',
            sharedNetwork: '185.220.101.x / ASN 13335',
            sharedMerchant: 'PeerTrade P2P Crypto Exchange',
            banksInvolved: ['Bank Alpha'],
            patternTitle: 'Coordinated Multi-Account Drain Originating on Shared Hardware',
          },
        },
        {
          id: `SIM-RING-2-${Date.now()}`,
          bankId: 'NOVA',
          bankName: 'Bank Nova',
          customerId: 'C1015',
          customerName: 'Rahul Varma',
          accountId: 'ACC-1015-MULE',
          transactionId: 'TXN-RING-NOVA-72K',
          amount: 72000,
          city: 'Pune',
          deviceId: 'DEV-RING-DEVICE-01',
          deviceLabel: 'Shared Hardware Rig',
          ipAddress: '185.220.101.12',
          merchant: 'PeerTrade P2P Crypto Exchange',
          timestamp: formatTime(2),
          attackType: 'CROSS_BANK_RING',
          stepIndex: 2,
          totalSteps: 3,
          riskScore: 90,
          riskLevel: 'CRITICAL',
          decision: 'BLOCK_AND_REVIEW',
          signals: ['Cross-bank device match', 'Same proxy subnet', 'Identical beneficiary signature'],
          summary: 'Bank Nova detected SAME device DEV-RING-DEVICE-01 attempting second ₹72,000 drain.',
          crossBankCorrelation: {
            sharedDevice: 'DEV-RING-DEVICE-01',
            sharedNetwork: '185.220.101.x / ASN 13335',
            sharedMerchant: 'PeerTrade P2P Crypto Exchange',
            banksInvolved: ['Bank Alpha', 'Bank Nova'],
            patternTitle: 'Cross-Bank Fraud Ring Detected: Synchronized Multi-Institution Strike',
          },
        },
        {
          id: `SIM-RING-3-${Date.now()}`,
          bankId: 'HORIZON',
          bankName: 'Bank Horizon',
          customerId: 'C1008',
          customerName: 'Sneha Reddy',
          accountId: 'ACC-1008-COMM',
          transactionId: 'TXN-RING-HORIZON-68K',
          amount: 68000,
          city: 'Pune',
          deviceId: 'DEV-RING-DEVICE-01',
          deviceLabel: 'Shared Hardware Rig',
          ipAddress: '185.220.101.99',
          merchant: 'PeerTrade P2P Crypto Exchange',
          timestamp: formatTime(4),
          attackType: 'CROSS_BANK_RING',
          stepIndex: 3,
          totalSteps: 3,
          riskScore: 100,
          riskLevel: 'CRITICAL',
          decision: 'BLOCK_AND_CREATE_CASE',
          signals: ['3-bank cluster confirmed', 'Simultaneous syndication', 'Shared hardware fingerprint'],
          summary: 'Third strike at Bank Horizon completes 3-bank fraud ring cluster. Interdiction enforced.',
          crossBankCorrelation: {
            sharedDevice: 'DEV-RING-DEVICE-01',
            sharedNetwork: '185.220.101.x / ASN 13335',
            sharedMerchant: 'PeerTrade P2P Crypto Exchange',
            banksInvolved: ['Bank Alpha', 'Bank Nova', 'Bank Horizon'],
            patternTitle: 'Confirmed 3-Bank Syndicated Fraud Ring: Complete Network Interdiction',
          },
        },
      ];

    case 'IMPOSSIBLE_TRAVEL':
      return [
        {
          id: `SIM-TRAVEL-1-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1004',
          customerName: 'Rajiv Sen',
          accountId: 'ACC-1004-PREMIUM',
          transactionId: 'TXN-TRAVEL-1-BLR',
          amount: 2500,
          city: 'Bengaluru',
          deviceId: 'DEV-1004-TRAVEL-A',
          deviceLabel: 'Recognized iPhone',
          ipAddress: '14.143.44.10',
          merchant: 'Bengaluru Cafe & Bistro',
          timestamp: formatTime(0),
          attackType: 'IMPOSSIBLE_TRAVEL',
          stepIndex: 1,
          totalSteps: 3,
          riskScore: 0,
          riskLevel: 'LOW',
          decision: 'ALLOW',
          signals: ['Normal POS purchase', 'Known device in home city'],
          summary: 'Legitimate morning coffee purchase in Bengaluru baseline territory.',
        },
        {
          id: `SIM-TRAVEL-2-${Date.now()}`,
          bankId: 'NOVA',
          bankName: 'Bank Nova',
          customerId: 'C1004',
          customerName: 'Rajiv Sen',
          accountId: 'ACC-1004-PREMIUM',
          transactionId: 'TXN-TRAVEL-2-MUM',
          amount: 45000,
          city: 'Mumbai',
          deviceId: 'DEV-1004-NEW-TAB',
          deviceLabel: 'Unverified Tablet',
          ipAddress: '49.36.128.55',
          merchant: 'Croma Electronics Mumbai',
          timestamp: formatTime(2),
          attackType: 'IMPOSSIBLE_TRAVEL',
          stepIndex: 2,
          totalSteps: 3,
          riskScore: 80,
          riskLevel: 'HIGH',
          decision: 'STEP_UP_VERIFICATION',
          signals: ['840 km distance in 4 minutes', '12,600 km/h velocity', 'New tablet device'],
          summary: 'Supersonic velocity anomaly: Bengaluru to Mumbai in 4 minutes violates physical laws.',
        },
        {
          id: `SIM-TRAVEL-3-${Date.now()}`,
          bankId: 'NOVA',
          bankName: 'Bank Nova',
          customerId: 'C1004',
          customerName: 'Rajiv Sen',
          accountId: 'ACC-1004-PREMIUM',
          transactionId: 'TXN-TRAVEL-3-MUM-PEAK',
          amount: 65000,
          city: 'Mumbai',
          deviceId: 'DEV-1004-NEW-TAB',
          deviceLabel: 'Unverified Tablet',
          ipAddress: '49.36.128.55',
          merchant: 'Luxury Watches & Timepieces',
          timestamp: formatTime(4),
          attackType: 'IMPOSSIBLE_TRAVEL',
          stepIndex: 3,
          totalSteps: 3,
          riskScore: 95,
          riskLevel: 'CRITICAL',
          decision: 'BLOCK_AND_REVIEW',
          signals: ['Confirmed impossible velocity', 'High-risk luxury MCC', 'Secondary drain attempt'],
          summary: 'Repeated high-value luxury transfer in impossible location window. Escalated to Block.',
        },
      ];

    case 'RAPID_BURST':
      return [
        {
          id: `SIM-BURST-1-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1001',
          customerName: 'Priya Sharma',
          accountId: 'ACC-1001-SAL',
          transactionId: 'TXN-BURST-1-8K',
          amount: 8000,
          city: 'Bengaluru',
          deviceId: 'DEV-1001-A',
          deviceLabel: 'Known Mobile',
          ipAddress: '122.167.45.12',
          merchant: 'Amazon India',
          timestamp: formatTime(0),
          attackType: 'RAPID_BURST',
          stepIndex: 1,
          totalSteps: 5,
          riskScore: 10,
          riskLevel: 'LOW',
          decision: 'ALLOW',
          signals: ['Baseline amount check', 'Standard e-commerce'],
          summary: 'Normal e-commerce order at baseline velocity.',
        },
        {
          id: `SIM-BURST-2-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1001',
          customerName: 'Priya Sharma',
          accountId: 'ACC-1001-SAL',
          transactionId: 'TXN-BURST-2-15K',
          amount: 15000,
          city: 'Bengaluru',
          deviceId: 'DEV-1001-A',
          deviceLabel: 'Known Mobile',
          ipAddress: '122.167.45.12',
          merchant: 'Flipkart Electronics',
          timestamp: formatTime(2),
          attackType: 'RAPID_BURST',
          stepIndex: 2,
          totalSteps: 5,
          riskScore: 40,
          riskLevel: 'MEDIUM',
          decision: 'STEP_UP_VERIFICATION',
          signals: ['Velocity acceleration (2s elapsed)', 'Amount doubling'],
          summary: 'Second transaction within 2 seconds. Velocity thresholds challenged.',
        },
        {
          id: `SIM-BURST-3-${Date.now()}`,
          bankId: 'HORIZON',
          bankName: 'Bank Horizon',
          customerId: 'C1001',
          customerName: 'Priya Sharma',
          accountId: 'ACC-1001-SAL',
          transactionId: 'TXN-BURST-3-35K',
          amount: 35000,
          city: 'Delhi',
          deviceId: 'DEV-1001-NEW-DESK',
          deviceLabel: 'New Web Session',
          ipAddress: '49.36.128.99',
          merchant: 'QuickPay Digital Gift Cards',
          timestamp: formatTime(4),
          attackType: 'RAPID_BURST',
          stepIndex: 3,
          totalSteps: 5,
          riskScore: 70,
          riskLevel: 'HIGH',
          decision: 'BLOCK_AND_REVIEW',
          signals: ['High-frequency carding burst', 'Gift card voucher MCC', '3x velocity peak'],
          summary: 'Gift card vouchers bought across secondary channel within 4s. Balance drain pattern.',
        },
        {
          id: `SIM-BURST-4-${Date.now()}`,
          bankId: 'NOVA',
          bankName: 'Bank Nova',
          customerId: 'C1001',
          customerName: 'Priya Sharma',
          accountId: 'ACC-1001-SAL',
          transactionId: 'TXN-BURST-4-65K',
          amount: 65000,
          city: 'Mumbai',
          deviceId: 'DEV-1001-NEW-DESK',
          deviceLabel: 'New Web Session',
          ipAddress: '103.21.144.11',
          merchant: 'Instant Crypto Wallet Refill',
          timestamp: formatTime(6),
          attackType: 'RAPID_BURST',
          stepIndex: 4,
          totalSteps: 5,
          riskScore: 85,
          riskLevel: 'HIGH',
          decision: 'BLOCK_AND_REVIEW',
          signals: ['Multi-channel drain', 'Crypto refill gateway', 'Critical cumulative velocity'],
          summary: 'High-speed balance liquidation across 3 payment channels in 6 seconds.',
        },
        {
          id: `SIM-BURST-5-${Date.now()}`,
          bankId: 'ALPHA',
          bankName: 'Bank Alpha',
          customerId: 'C1001',
          customerName: 'Priya Sharma',
          accountId: 'ACC-1001-SAL',
          transactionId: 'TXN-BURST-5-95K',
          amount: 95000,
          city: 'Bengaluru',
          deviceId: 'DEV-1001-NEW-DESK',
          deviceLabel: 'Automated Bot Script',
          ipAddress: '103.21.144.11',
          merchant: 'Gold Bullion Online Delivery',
          timestamp: formatTime(8),
          attackType: 'RAPID_BURST',
          stepIndex: 5,
          totalSteps: 5,
          riskScore: 100,
          riskLevel: 'CRITICAL',
          decision: 'BLOCK_AND_CREATE_CASE',
          signals: [
            'Total drain ceiling reached',
            '5 transactions in 8 seconds',
            'Automated scripted velocity',
            'Escalating balance depletion'
          ],
          summary: 'Maximum balance depletion spike reached. Scripted burst blocked by FinGuard.',
        },
      ];
  }
}
